### ISSUE TITLE
capture frames on EXIT_FRAME instead of ENTER_FRAME

### ISSUE THREAD

**Issue by onedrop** [CreateJS/Zoe#10]
I have a swf of a game character and it has some timeline code to color certain features of the character. I want to use Zoe to export spritesheets of that character in several different color combinations simply by changing some initial variables. 

I'm getting mixed results. The spritesheet that Zoe generates does not always color every feature on every frame. 

My thought was to change the CaptureSWF util class to run on EXIT_FRAME instead of ENTER_FRAME so that each frame's scripts would have a chance to run.

I could be wrong though, a render may not have occurred at that point. Any thoughts on this? Is what I want to achieve beyond the scope of Zoe?

**Comment by lannymcnie** [comment]
Good suggestion. We will look into it.

**Comment by onedrop** [comment]
Thanks. I ened up writing a JSFL script to recolor the character's library symbols. This way I don't have to do any coloring at runtime and I can just publish it and import it into Zoe.

**Comment by wdamien** [comment]
Can you try this new build I uploaded here -> [Zoe_v0_3_4.zip](http://community.createjs.com/discussions/zoe/62/assets/54f7ff1d8db95c89e6ac32d607b0391d9331c030/Zoe_v0_3_4.zip)?  I changed all the capture code to use EXIT_FRAME, so it should resolve your issue.

**Comment by wdamien** [comment]
This has been fixed with the public version of zoe.
