### ISSUE TITLE
variable frame positioning

### ISSUE THREAD

**Issue by daanporon** [CreateJS/Zoe#11]
Hi, when i choose for a variable frame it seems the positioning of the frame isn't exported in the JSON ...  Shouldn't the regX and regY variable point to the right position (http://www.createjs.com/Docs/EaselJS/SpriteSheet.html)? Or how will easeljs know where to place the current frame?

**Comment by wdamien** [comment]
The newer versions of Zoe have various fixes for JSON export, and this will be resolved.
