### ISSUE TITLE
Support 1024x1024 dimension (or custom base 2 dimensions?)

### ISSUE THREAD

**Issue by Glidias** [CreateJS/Zoe#3]
Yes, as the title suggests. Because older IOS non-retina displays may need to use smaller sprite sheets. Currently, i have a commit here to support smaller base 2 sizes: https://github.com/Glidias/Zoe/commit/6e631334bba9f50d9a671a0da94e1e35bfc40a79

**Comment by wdamien** [comment]
Manually merged here: c51ca87e678e866f9c9c7b9407a429b21b983234
