### ISSUE TITLE
why flash8 is'nt supported?

### ISSUE THREAD

**Issue by cubemoon** [CreateJS/Zoe#5]
why flash8 is'nt supported?.if zoe can support flash8, will be great.

**Comment by wdamien** [comment]
Its because Zoe needs to interact with the loaded swf, like control the timeline, read keyframes and labels, also pull a custom registration point from the loaded swf.  Its simply technically not possible to have this level of interaction with older AVM1 (as2 or as1) swfs.

**Comment by cubemoon** [comment]
Thank you for your reply.
Can not find a way to deal with Flash8?  I really hope that Zoe can deal with Flash8.

**Comment by lannymcnie** [comment]
Flash 9 has been public almost 6 years - so it is unlikely we will do any work to support earlier versions.

**Comment by bobbycool1992** [comment]
Hi zoe developer , 
Can you give me the link so i can download zoe app which have EASLJS option for export ? I have zoe , but the GUI don't have the EASELJS export like this image attached . Many thanks :+1: 
![capts](https://cloud.githubusercontent.com/assets/7400576/3009912/546b17a4-df0b-11e3-8464-b43c5d91bbf0.PNG)

**Comment by wdamien** [comment]
@bobbycool1992 you can always download the latest Zoé here; http://createjs.com/#!/Zoe/download the JSON export type is compatible with EaselJS.
