### ISSUE TITLE
Exporting omits offset

### ISSUE THREAD

**Issue by naranjamecanica** [CreateJS/Zoe#6]
Since version 3.0 the exporting misses the offset values. I need those to properly render an animation with the trimmed frames.

Zoe 2.0

``` json
 "frames": [
        [556, 0, 175, 194, 0, -5, -94],
        [381, 0, 175, 196, 0, -5, -91],
        [900, 547, 177, 143, 0, -4, -147],
        [539, 547, 179, 145, 0, -4, -145],
```

Zoe 3.0+

``` json
 "frames": [
        [1109, 382, 183, 156, 0, 0, 0],
        [741, 382, 183, 159, 0, 0, 0],
        [370, 382, 185, 162, 0, 0, 0],
        [0, 382, 184, 165, 0, 0, 0],
```

**Comment by wdamien** [comment]
There were a few improvements to how registration points are handled in the latest version of Zoe, the way they're exported is correct now. If you don't include a registrationPoint clip in the fla, the regX and regY will default to zero.   So if you add a empty movie clip to your stage and name it registrationPoint, your points should export correctly.

**Comment by naranjamecanica** [comment]
But how do you know the reg point of a trimmed frame? All the frames can have a different size and reg point, the way Zoe 2 handled this sounds more dynamic? 

Edit: I'm sorry I should actually test this first before I comment, the points are probably calculated from this clip and not just set to the actual  X/y values. If not I'll get back to this issue.

**Comment by josimard** [comment]
I had the same problem, even while adding the registrationPoint clip (at Point(0,0) ).

I fixed the issue putting the registrationPoint clip at the Point(1,1) and now it exports the offsets correctly.
